added cleanup to ubuntu_test

diff --git a/.github/workflows/ubuntu_test.yml b/.github/workflows/ubuntu_test.yml
--- a/.github/workflows/ubuntu_test.yml
+++ b/.github/workflows/ubuntu_test.yml
@@ -62,7 +62,7 @@ jobs:
         run: |
           docker build \
             --target runtime \
-            -t abaer1902/avalonia-app:runtime \
+            -t abaer1902/avalonia-runtime:latest \
             .
 
       # Smoke test runtime image
@@ -73,7 +73,7 @@ jobs:
 
           docker run --rm \
             --entrypoint /bin/bash \
-            abaer1902/avalonia-app:runtime \
+            abaer1902/avalonia-runtime:latest \
             -c 'timeout --foreground -k 2s 10s xvfb-run -a dotnet AvaloniaApplication1.dll'
 
           exit_code=$?
@@ -104,12 +104,12 @@ jobs:
         run: |
           mkdir -p artifacts
 
-          if docker image inspect abaer1902/avalonia-app:runtime >/dev/null 2>&1; then
+          if docker image inspect abaer1902/abaer1902/avalonia-runtime:latest >/dev/null 2>&1; then
             echo "Docker image exists. Saving image artifact."
 
             docker save \
               -o artifacts/avalonia-app-test.tar \
-              abaer1902/avalonia-app:runtime
+              abaer1902/abaer1902/avalonia-runtime:latest
           else
             echo "Image does not exist; skipping."
           fi
@@ -129,7 +129,7 @@ jobs:
         shell: bash
         run: |
           docker tag \
-            abaer1902/avalonia-app:runtime \
+            abaer1902/abaer1902/avalonia-runtime:latest \
             abaer1902/avalonia-app:latest
 
           docker push \
@@ -140,3 +140,12 @@ jobs:
         if: ${{ success() }}
         run: |
           docker push abaer1902/avalonia-build:latest
+
+
+      # Cleanup
+      - name: Clean temporary Docker resources
+        if: ${{ always() }}
+        run: |
+          docker image rm abaer1902/avalonia-runtime:latest || true
+          docker image rm abaer1902/avalonia-build:latest || true
+          
